### ISSUE TITLE
feat(server): multiple

### ISSUE THREAD

**Issue by chrisp60** [chrisp60/guppee#13]
Moving here from #12

## TODO:
* [x] Remove players from the pool on `Message::Closed`.
* [x] Client side javascript for initial page visit.
* [x] Populate player list with forms to select an opponent.
* [x] Update player list when player disconnects.
* [ ] Properly model API.
* [ ] Unity plugin to call push & pull updates from javascript socket.
* [ ] Nicknames for connected sockets that can be set by user.
* [ ] Ref: change server to only send player list on change instead of pinging it every few seconds.
* [ ] Client side notification when a player invites you to a game.
* [ ] Form for accepting players invite.
* [ ] Loading unity into canvas on game start.
* [ ] Proxy messages between two players in game.
